AWSTemplateFormatVersion: '2010-09-09'
Description: ETL Pipeline completo con S3, EventBridge, Lambda, Step Functions, Glue y Athena

Parameters:
  ArtifactsBucket:
    Type: String
    Description: Nombre del bucket S3 donde están los scripts (creado manualmente)
  
  GlueScriptBronzeKey:
    Type: String
    Description: Ruta del script de Glue bronze en el bucket
    Default: scripts/bronze/ecommerce-glue-job-bronze.py

  GlueScriptSilverKey:
    Type: String
    Description: Ruta del script de Glue silver en el bucket
    Default: scripts/silver/ecommerce-glue-job-silver.py
  
  LambdaPackageKey:
    Type: String
    Description: Ruta del zip de Lambda en el bucket
    Default: lambda/lambda.zip
  
  StepFunctionKey:
    Type: String
    Description: Ruta de la definición de Step Function
    Default: stepfunctions/ecommerce-step.json
  
  EnvironmentName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod

Resources:
# ---------------- S3 ----------------
  DataLakeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'data-science-retail-bucket-iac-${EnvironmentName}-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

# ---------------- IAM ----------------
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "retail-lambda-role-iac-${EnvironmentName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref StepFunction
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"

  StepFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "retail-step-role-iac-${EnvironmentName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepGluePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - glue:StartJobRun
                  - glue:GetJobRun
                Resource: "*"

  GlueRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "retail-glue-role-iac-${EnvironmentName}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GluePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource: "*"

# ---------------- LAMBDA ----------------
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "retail-lambda-iac-${EnvironmentName}"
      Runtime: python3.12
      Handler: ecommerce-lambda.lambda_handler
      Role: !GetAtt LambdaRole.Arn
      Timeout: 60
      Environment:
        Variables:
          STEP_ARN: !Ref StepFunction
      Code:
        S3Bucket: !Ref ArtifactsBucket
        S3Key: !Ref LambdaPackageKey

# ---------------- GLUE ----------------
  GlueJobBronze:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "retail-glue-job-bronze-iac-${EnvironmentName}"
      Role: !GetAtt GlueRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${ArtifactsBucket}/${GlueScriptBronzeKey}"
        PythonVersion: 3
      GlueVersion: "5.0"
      DefaultArguments:
        "--enable-glue-datacatalog": "true"
        "--job-language": "python"
        "--TempDir": !Sub "s3://${DataLakeBucket}/temp/"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"

  GlueJobSilver:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "retail-glue-job-silver-iac-${EnvironmentName}"
      Role: !GetAtt GlueRole.Arn
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://${ArtifactsBucket}/${GlueScriptSilverKey}"
        PythonVersion: 3
      GlueVersion: "5.0"
      DefaultArguments:
        "--enable-glue-datacatalog": "true"
        "--job-language": "python"
        "--TempDir": !Sub "s3://${DataLakeBucket}/temp/"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"

# ---------------- STEP FUNCTION ----------------
  StepFunction:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "retail-step-iac-${EnvironmentName}"
      RoleArn: !GetAtt StepFunctionRole.Arn
      DefinitionS3Location:
        Bucket: !Ref ArtifactsBucket
        Key: !Ref StepFunctionKey

# ---------------- EVENTBRIDGE ----------------
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "retail-event-iac-${EnvironmentName}"
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - !Ref DataLakeBucket
          object:
            key:
              - prefix: "bronze/"
      Targets:
        - Arn: !GetAtt LambdaFunction.Arn
          Id: LambdaTarget

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventRule.Arn

# ---------------- ATHENA (GLUE CATALOG) ----------------
  AthenaDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub "retail_db_${EnvironmentName}"

  AthenaBronzeTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref AthenaDatabase
      TableInput:
        Name: retail_bronze
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        StorageDescriptor:
          Location: !Sub "s3://${DataLakeBucket}/bronze/"
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Columns:
            - Name: InvoiceNo
              Type: string
            - Name: StockCode
              Type: string
            - Name: Description
              Type: string
            - Name: Quantity
              Type: int
            - Name: InvoiceDate
              Type: string
            - Name: UnitPrice
              Type: double
            - Name: CustomerID
              Type: string
            - Name: Country
              Type: string

# ---------------- OUTPUTS ----------------
Outputs:
  DataLakeBucket:
    Description: Data lake bucket name
    Value: !Ref DataLakeBucket
  
  ArtifactsBucket:
    Description: Artifacts bucket name (created manually)
    Value: !Ref ArtifactsBucket
  
  LambdaFunction:
    Description: Lambda function name
    Value: !Ref LambdaFunction
  
  StepFunction:
    Description: Step Function ARN
    Value: !Ref StepFunction
  
  GlueJobBronze:
    Description: Glue job bronze name
    Value: !Ref GlueJobBronze

  GlueJobSilver:
    Description: Glue job silver name
    Value: !Ref GlueJobSilver
  
  AthenaDatabase:
    Description: Athena database name
    Value: !Ref AthenaDatabase